version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-extractor
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
      - ./../storage/:/opt/www/storage
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
  db:
    container_name: hyperf-db
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    command: -c 'max_connections=500'
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ex4mpl3
    volumes:
      - ./../initdb:/docker-entrypoint-initdb.d

networks:
  default:
    name: hyperf-skeleton
